#!/usr/bin/env python3
"""
Generate Blocky configs for smart DNS modes on the Freebox VM.

Chain (every filtered mode):
  1) local hosts (anti-lie)  →  2) denylist groups  →  3) Unbound 172.28.0.10
     Unbound: local-data + DoT forward-first + root / serve-expired

Modes:
  malware  — malware / phishing only
  antipub  — intelligent ads + trackers + anti–anti-adblock (no malware lists)
  secure   — full: antipub + malware

Uncensored mode is dns-libre (dnsproxy), not Blocky.

Usage:
  python3 scripts/generate-blocky-modes.py
"""
from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "config" / "blocky"

DENYLISTS = """
  denylists:
    pihole:
      - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
      - https://adaway.org/hosts.txt
      - https://raw.githubusercontent.com/anudeepND/blacklist/master/adservers.txt
      - https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext
      - https://v.firebog.net/hosts/Prigent-Ads.txt
      - /app/lists/ads-extra.txt
    ublock:
      - https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/wildcard/multi.txt
      - https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/wildcard/popupads.txt
      - https://v.firebog.net/hosts/Easyprivacy.txt
      - https://v.firebog.net/hosts/AdguardDNS.txt
      - https://small.oisd.nl/
    anti_adblock:
      - https://v.firebog.net/hosts/Admiral.txt
      - /app/lists/anti-adblock.txt
    malware:
      - https://urlhaus.abuse.ch/downloads/hostfile/
      - https://raw.githubusercontent.com/Spam404/lists/master/main-blacklist.txt
      - https://raw.githubusercontent.com/PolishFiltersTeam/KADhosts/master/KADhosts.txt
      - https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Alternate%20versions%20Anti-Malware%20List/AntiMalwareHosts.txt
      - https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/wildcard/tif.medium.txt
      - /app/lists/malware-extra.txt
  allowlists:
    pihole:
      - /app/lists/allowlist.txt
    ublock:
      - /app/lists/allowlist.txt
    anti_adblock:
      - /app/lists/allowlist.txt
    malware:
      - /app/lists/allowlist.txt
""".rstrip()

COMMON_HEAD = """# Auto-generated by scripts/generate-blocky-modes.py — do not hand-edit.
# Mode: {mode} — {title}
# Smart split: LOCAL hosts → Blocky groups → Unbound (DoT forward-first) → world
# See docs/modes.md

upstreams:
  groups:
    default:
      # Shared resilient resolver (local-data + DoT uncensoring + serve-expired)
      - 172.28.0.10
  strategy: parallel_best
  timeout: 3s

connectIPVersion: dual

bootstrapDns:
  - tcp+udp:9.9.9.10
  - tcp+udp:194.242.2.2
  - tcp+udp:94.140.14.140

# 1) LOCAL truthful hosts BEFORE any denylist (anti–DNS menteur)
hostsFile:
  sources:
    - /app/uncensor/hosts.critical
    - /app/uncensor/hosts.local
    - /app/uncensor/hosts.generated
  hostsTTL: 24h
  filterLoopback: false

blocking:
{denylists}
  clientGroupsBlock:
    default:
{groups}
  blockType: nxDomain
  blockTTL: 6h
  loading:
    refreshPeriod: 12h
    strategy: blocking
    concurrency: 4
    downloads:
      timeout: 120s
      attempts: 3

caching:
  minTime: 5m
  maxTime: 24h
  prefetching: true
  cacheTimeNegative: 30m

ports:
  dns: 53
  http: 4000
  https: 443
  tls: 853

certFile: /app/certs/server.crt
keyFile: /app/certs/server.key

prometheus:
  enable: false

log:
  level: info
  format: text
  privacy: true
{querylog}
"""

QUERYLOG_SECURE = """
# Pi-hole-like local query log (CSV on VM disk only — not cloud)
queryLog:
  type: csv
  target: /app/querylog
  logRetentionDays: 7
"""

MODES = {
    "malware": {
        "file": "config-malware.yml",
        "title": "malware-free (threats only, no ads filter)",
        "groups": ["malware"],
        "querylog": "",
    },
    "antipub": {
        "file": "config-antipub.yml",
        "title": "antipub intelligent (Pi-hole + uBlock DNS + anti–anti-adblock)",
        "groups": ["pihole", "ublock", "anti_adblock"],
        "querylog": "",
    },
    "secure": {
        "file": "config.yml",
        "title": "secure full (antipub + malware) + Pi-hole-like CSV query log",
        "groups": ["pihole", "ublock", "anti_adblock", "malware"],
        "querylog": QUERYLOG_SECURE,
    },
}


def render(mode: str, meta: dict) -> str:
    groups = "\n".join(f"      - {g}" for g in meta["groups"])
    return COMMON_HEAD.format(
        mode=mode,
        title=meta["title"],
        denylists=DENYLISTS,
        groups=groups,
        querylog=meta.get("querylog", ""),
    )


def main() -> int:
    OUT.mkdir(parents=True, exist_ok=True)
    for mode, meta in MODES.items():
        path = OUT / meta["file"]
        path.write_text(render(mode, meta) + "\n", encoding="utf-8")
        print("wrote", path.relative_to(ROOT), "groups=", meta["groups"])
    catalog = {
        "title": "Smart spit — 4 DNS modes",
        "doc": "docs/modes.md",
        "smart_split": [
            "1_local_hosts_uncensor",
            "2_mode_filter",
            "3_unbound_forward_first_dot",
            "4_root_or_serve_expired_or_dnsproxy_fallbacks",
        ],
        "modes": {
            "uncensored": {
                "engine": "dnsproxy",
                "service": "dns-libre",
                "port_lab": 5356,
                "port_prod": 53,
                "doh": 8453,
                "dot_lab": 8853,
                "dot_prod": 853,
                "doq_lab": 8853,
                "filter": [],
                "order": "hosts → Unbound → (dnsproxy fallbacks)",
                "note": "No denylist — local hosts then Unbound; dnsproxy fallbacks if Unbound down",
            },
            "malware": {
                "engine": "blocky",
                "service": "dns-malware",
                "config": "config/blocky/config-malware.yml",
                "port_lab": 5357,
                "port_prod": 5357,
                "doh": 8445,
                "dot_lab": 8855,
                "filter": ["malware"],
                "order": "hosts → malware denylist → Unbound",
            },
            "antipub": {
                "engine": "blocky",
                "service": "dns-antipub",
                "config": "config/blocky/config-antipub.yml",
                "port_lab": 5358,
                "port_prod": 5358,
                "doh": 8446,
                "dot_lab": 8856,
                "filter": ["pihole", "ublock", "anti_adblock"],
                "order": "hosts → pihole + ublock + anti_adblock → Unbound",
            },
            "secure": {
                "engine": "blocky",
                "service": "dns-secure",
                "config": "config/blocky/config.yml",
                "port_lab": 5354,
                "port_prod": 5354,
                "doh": 8444,
                "dot_lab": 8854,
                "filter": ["pihole", "ublock", "anti_adblock", "malware"],
                "order": "hosts → pihole + ublock + anti_adblock + malware → Unbound",
                "queryLog": "csv:/app/querylog",
                "ui": ":3080",
            },
        },
        "dhcp": {
            "dns1": "HOST_IP (uncensored / dns-libre :53 prod)",
            "dns2_sos": "9.9.9.10",
            "note": "DNS1 = this project. DNS2 = SOS if the host is down. Other modes via DoH / alternate ports.",
        },
    }
    import json

    (OUT / "modes.json").write_text(json.dumps(catalog, indent=2) + "\n", encoding="utf-8")
    print("wrote", (OUT / "modes.json").relative_to(ROOT))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
