#!/usr/bin/env python3
"""
OONI-inspired anti–DNS-menteur probe.
Compare liar resolvers (Freebox gateway / Free ISP) vs uncensoring controls.
When ISP lies (NXDOMAIN / 127.0.0.1 / private sinkhole) but controls agree on
public A/AAAA, write local overrides used BEFORE upstream forward.

Refs:
  - https://ooni.org/post/2025-france-report/
  - Citizen Lab test-lists (fr.csv)
"""
from __future__ import annotations

import ipaddress
import json
import os
import re
import subprocess
import sys
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
UNC = ROOT / "config" / "uncensor"
SIG = json.loads((UNC / "sinkhole-signatures.json").read_text(encoding="utf-8"))
TARGETS = UNC / "probe-targets.txt"
OUT_HOSTS = UNC / "hosts.generated"
OUT_UNBOUND = ROOT / "config" / "unbound" / "a-records.conf"
OUT_BLOCKY = UNC / "blocky-custom-dns.yml"
OUT_REPORT = UNC / "last-probe-report.json"


def dig(server: str, name: str, qtype: str) -> list[str]:
    try:
        p = subprocess.run(
            [
                "dig",
                f"@{server}",
                name,
                qtype,
                "+time=3",
                "+tries=1",
                "+short",
            ],
            capture_output=True,
            text=True,
            timeout=8,
            check=False,
        )
    except (FileNotFoundError, subprocess.TimeoutExpired):
        return []
    out = []
    for line in (p.stdout or "").splitlines():
        line = line.strip()
        if not line or line.startswith(";"):
            continue
        # CNAME lines may appear first
        if re.match(r"^[A-Za-z0-9._-]+\.$", line):
            continue
        out.append(line.rstrip("."))
    return out


def is_lie_answer(addrs: list[str], nx: bool) -> bool:
    if nx or not addrs:
        return True
    for a in addrs:
        if a in SIG["lie_answers_ipv4"] or a in ("::1",):
            return True
        for pfx in SIG["lie_private_prefixes"]:
            if a.startswith(pfx):
                return True
        try:
            ip = ipaddress.ip_address(a)
            if ip.is_loopback or ip.is_private or ip.is_link_local or ip.is_unspecified:
                return True
        except ValueError:
            continue
    return False


def is_public(addr: str) -> bool:
    try:
        ip = ipaddress.ip_address(addr)
        return not (
            ip.is_loopback
            or ip.is_private
            or ip.is_link_local
            or ip.is_multicast
            or ip.is_unspecified
            or ip.is_reserved
        )
    except ValueError:
        return False


def consensus(servers: list[str], name: str, qtype: str) -> list[str]:
    bag: Counter[str] = Counter()
    for s in servers:
        for a in dig(s, name, qtype):
            if is_public(a):
                bag[a] += 1
    if not bag:
        return []
    # Keep answers seen on >=2 controls, else top answer if only one control replied
    best = bag.most_common()
    thresh = 2 if sum(1 for _ in servers) >= 3 else 1
    chosen = [a for a, n in best if n >= thresh]
    if not chosen and best:
        chosen = [best[0][0]]
    return chosen[:4]


def load_targets() -> list[str]:
    domains = []
    for line in TARGETS.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        domains.append(line.lower().rstrip("."))
    return domains


def main() -> int:
    liars = SIG["liar_resolvers"]
    controls = SIG["control_resolvers"]
    report = {"lies_corrected": [], "clean": [], "unknown": []}
    host_lines = [
        "# Generated by scripts/ooni-like-anti-lie.py — OONI-like DNS consistency",
        "# Served locally BEFORE upstream forward (dns-libre / unbound / blocky)",
        "",
    ]
    unbound_lines = [
        "# Generated local-data — truthful A/AAAA before DoT forward",
        "server:",
    ]
    blocky_map: dict[str, str] = {}

    for domain in load_targets():
        liar_a: list[str] = []
        liar_nx = True
        for liar in liars:
            ans = dig(liar, domain, "A")
            if ans:
                liar_a = ans
                liar_nx = False
                break
            # empty → try next liar; if all empty treat as NX
        lied = is_lie_answer(liar_a, liar_nx)

        ctrl_a = consensus(controls, domain, "A")
        ctrl_aaaa = consensus(controls, domain, "AAAA")

        if not ctrl_a and not ctrl_aaaa:
            report["unknown"].append({"domain": domain, "reason": "no_control_answer"})
            continue

        if not lied:
            report["clean"].append(
                {"domain": domain, "liar_a": liar_a, "control_a": ctrl_a}
            )
            # Still optional: cache control answers locally for resilience
            # Only write overrides when a lie was detected (strict mode)
            continue

        entry = {
            "domain": domain,
            "liar_a": liar_a,
            "liar_nx": liar_nx,
            "control_a": ctrl_a,
            "control_aaaa": ctrl_aaaa,
        }
        report["lies_corrected"].append(entry)

        for ip in ctrl_a:
            host_lines.append(f"{ip} {domain}")
            unbound_lines.append(f'  local-data: "{domain}. IN A {ip}"')
        for ip in ctrl_aaaa:
            host_lines.append(f"{ip} {domain}")
            unbound_lines.append(f'  local-data: "{domain}. IN AAAA {ip}"')
        if ctrl_a:
            blocky_map[domain] = ctrl_a[0]

    OUT_HOSTS.write_text("\n".join(host_lines) + "\n", encoding="utf-8")
    OUT_UNBOUND.write_text("\n".join(unbound_lines) + "\n", encoding="utf-8")

    # Blocky customDNS fragment
    yml = ["# Generated — include via blocky customDNS mapping merge", "customDNS:", "  mapping:"]
    if blocky_map:
        for d, ip in sorted(blocky_map.items()):
            yml.append(f"    {d}: {ip}")
    else:
        yml.append("    # (no lie corrections this run)")
    OUT_BLOCKY.write_text("\n".join(yml) + "\n", encoding="utf-8")

    OUT_REPORT.write_text(json.dumps(report, indent=2), encoding="utf-8")
    print(
        f"corrected={len(report['lies_corrected'])} "
        f"clean={len(report['clean'])} unknown={len(report['unknown'])}"
    )
    print(f"wrote {OUT_HOSTS}")
    print(f"wrote {OUT_UNBOUND}")
    print(f"wrote {OUT_BLOCKY}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
