#!/usr/bin/env python3
"""
Warm local critical DNS seeds for project resilience.

Writes:
  - config/uncensor/hosts.critical     (edge: dnsproxy / Blocky — LOCAL FIRST)
  - config/unbound/a-records.critical.conf  (Unbound local-zone + local-data)

Unbound order (inside container):
  local-data/critical → cache/serve-expired → DoT forwards → root

Controls prefer plain-UDP SOS reachable on FR Free ISP.
"""
from __future__ import annotations

import ipaddress
import socket
import struct
import sys
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
UNC = ROOT / "config" / "uncensor"
TARGETS = (UNC / "critical-targets.txt").read_text(encoding="utf-8").splitlines()
OUT = UNC / "hosts.critical"
OUT_UNBOUND = ROOT / "config" / "unbound" / "a-records.critical.conf"
# Prefer SOS UDP-reachable; keep DoT-only peers as soft extras
CONTROLS = [
    "9.9.9.10",
    "194.242.2.2",
    "94.140.14.140",
    "149.112.112.10",
    "193.110.81.254",
]


def dig_udp(server: str, name: str, qtype: str = "A", timeout: float = 3.0) -> list[str]:
    """Minimal DNS A/AAAA via UDP (works on Windows without dig)."""
    qtype_num = {"A": 1, "AAAA": 28}.get(qtype.upper())
    if qtype_num is None:
        return []
    labels = name.strip(".").split(".")
    qname = b"".join(bytes([len(l)]) + l.encode("idna", "strict") for l in labels) + b"\x00"
    header = struct.pack("!HHHHHH", 0x1234, 0x0100, 1, 0, 0, 0)
    question = qname + struct.pack("!HH", qtype_num, 1)
    pkt = header + question
    sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    sock.settimeout(timeout)
    try:
        sock.sendto(pkt, (server, 53))
        data, _ = sock.recvfrom(4096)
    except OSError:
        return []
    finally:
        sock.close()
    if len(data) < 12:
        return []
    _, flags, qd, an, _, _ = struct.unpack("!HHHHHH", data[:12])
    if (flags & 0x8000) == 0 or an == 0:
        return []
    # skip question
    i = 12
    for _ in range(qd):
        while i < len(data) and data[i] != 0:
            if data[i] & 0xC0 == 0xC0:
                i += 2
                break
            i += 1 + data[i]
        else:
            i += 1
        i += 4
    out: list[str] = []
    for _ in range(an):
        if i >= len(data):
            break
        if data[i] & 0xC0 == 0xC0:
            i += 2
        else:
            while i < len(data) and data[i] != 0:
                i += 1 + data[i]
            i += 1
        if i + 10 > len(data):
            break
        rtype, _, _, rdlen = struct.unpack("!HHIH", data[i : i + 10])
        i += 10
        rdata = data[i : i + rdlen]
        i += rdlen
        try:
            if rtype == 1 and rdlen == 4:
                ip = str(ipaddress.IPv4Address(rdata))
            elif rtype == 28 and rdlen == 16:
                ip = str(ipaddress.IPv6Address(rdata))
            else:
                continue
            addr = ipaddress.ip_address(ip)
            if not (addr.is_private or addr.is_loopback or addr.is_unspecified):
                out.append(ip)
        except ValueError:
            continue
    return out


def consensus(name: str, qtype: str) -> list[str]:
    bag: Counter[str] = Counter()
    for s in CONTROLS:
        for a in dig_udp(s, name, qtype):
            bag[a] += 1
    if not bag:
        return []
    best = bag.most_common()
    chosen = [a for a, n in best if n >= 2] or [best[0][0]]
    return chosen[:3]


def main() -> int:
    lines = [
        "# Critical project seeds — LOCAL FIRST (edge dnsproxy/Blocky)",
        "# Generated by scripts/warm-local-cache.py",
        "192.168.1.254 mafreebox.freebox.fr",
        "192.168.1.254 mafreebox",
        "",
    ]
    ulines = [
        "# Critical Unbound local zones — LOCAL FIRST (before DoT forwards)",
        "# Generated by scripts/warm-local-cache.py",
        "# typetransparent: answer A/AAAA from local-data; other types may still recurse",
        "",
    ]
    domains = [
        t.strip().lower().rstrip(".")
        for t in TARGETS
        if t.strip() and not t.strip().startswith("#")
    ]
    seen_zones: set[str] = set()
    for d in domains:
        a_recs = consensus(d, "A")
        aaaa_recs = consensus(d, "AAAA")
        if not a_recs and not aaaa_recs:
            continue
        if d not in seen_zones:
            ulines.append(f'local-zone: "{d}." typetransparent')
            seen_zones.add(d)
        for ip in a_recs:
            lines.append(f"{ip} {d}")
            ulines.append(f'local-data: "{d}. IN A {ip}"')
        for ip in aaaa_recs:
            lines.append(f"{ip} {d}")
            ulines.append(f'local-data: "{d}. IN AAAA {ip}"')
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    OUT_UNBOUND.write_text("\n".join(ulines) + "\n", encoding="utf-8")
    print(f"wrote {OUT} ({len(lines)} lines)")
    print(f"wrote {OUT_UNBOUND} ({len(seen_zones)} zones)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
