#!/usr/bin/env python3
"""
Warm local critical DNS seeds for project resilience.
Resolves critical-targets.txt via control resolvers and writes hosts.critical
(+ unbound local-data append file). LOCAL layer survives when public DNS dies.
"""
from __future__ import annotations

import ipaddress
import subprocess
import sys
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
UNC = ROOT / "config" / "uncensor"
TARGETS = (UNC / "critical-targets.txt").read_text(encoding="utf-8").splitlines()
OUT = UNC / "hosts.critical"
OUT_UNBOUND = ROOT / "config" / "unbound" / "a-records.critical.conf"
CONTROLS = [
    "91.239.100.100",
    "185.95.218.42",
    "9.9.9.10",
    "194.242.2.2",
    "193.110.81.254",
]


def dig(server: str, name: str, qtype: str) -> list[str]:
    try:
        p = subprocess.run(
            ["dig", f"@{server}", name, qtype, "+time=3", "+tries=1", "+short"],
            capture_output=True,
            text=True,
            timeout=8,
            check=False,
        )
    except (FileNotFoundError, subprocess.TimeoutExpired):
        return []
    out = []
    for line in (p.stdout or "").splitlines():
        line = line.strip().rstrip(".")
        if not line or " " in line:
            # skip CNAME target lines that look like hostnames without being IPs
            try:
                ipaddress.ip_address(line)
            except ValueError:
                continue
        try:
            ip = ipaddress.ip_address(line)
            if not (ip.is_private or ip.is_loopback or ip.is_unspecified):
                out.append(line)
        except ValueError:
            continue
    return out


def consensus(name: str, qtype: str) -> list[str]:
    bag: Counter[str] = Counter()
    for s in CONTROLS:
        for a in dig(s, name, qtype):
            bag[a] += 1
    if not bag:
        return []
    best = bag.most_common()
    chosen = [a for a, n in best if n >= 2] or [best[0][0]]
    return chosen[:3]


def main() -> int:
    lines = [
        "# Critical project seeds — LOCAL FIRST",
        "# Generated by scripts/warm-local-cache.py",
        "192.168.1.254 mafreebox.freebox.fr",
        "192.168.1.254 mafreebox",
        "",
    ]
    ulines = [
        "# Critical local-data — included after a-records.conf",
    ]
    domains = [
        t.strip().lower().rstrip(".")
        for t in TARGETS
        if t.strip() and not t.strip().startswith("#")
    ]
    for d in domains:
        for ip in consensus(d, "A"):
            lines.append(f"{ip} {d}")
            ulines.append(f'local-data: "{d}. IN A {ip}"')
        for ip in consensus(d, "AAAA"):
            lines.append(f"{ip} {d}")
            ulines.append(f'local-data: "{d}. IN AAAA {ip}"')
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    OUT_UNBOUND.write_text("\n".join(ulines) + "\n", encoding="utf-8")
    print(f"wrote {OUT} ({len(lines)} lines)")
    print(f"wrote {OUT_UNBOUND}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
