# Critical local-data — included after a-records.conf
local-data: "github.com. IN A 140.82.121.4"
local-data: "raw.githubusercontent.com. IN A 185.199.110.133"
local-data: "raw.githubusercontent.com. IN AAAA 2606:50c0:8003::154"
local-data: "api.github.com. IN A 140.82.121.6"
local-data: "ghcr.io. IN A 140.82.121.34"
local-data: "registry-1.docker.io. IN A 52.45.63.121"
local-data: "registry-1.docker.io. IN AAAA 2600:1f18:2148:bc01:8ae3:3249:7454:6f0d"
local-data: "auth.docker.io. IN A 172.64.144.78"
local-data: "auth.docker.io. IN AAAA 2606:4700:4403::ac40:904e"
local-data: "production.cloudflare.docker.com. IN A 104.16.101.215"
local-data: "production.cloudflare.docker.com. IN AAAA 2606:4700::6810:62d7"
local-data: "cloud.debian.org. IN A 194.71.11.165"
local-data: "cloud.debian.org. IN AAAA 2001:6b0:19::163"
local-data: "mullvad.net. IN A 45.83.223.209"
local-data: "dns.mullvad.net. IN A 194.242.2.2"
local-data: "dns.mullvad.net. IN AAAA 2a07:e340::2"
local-data: "dns.digitale-gesellschaft.ch. IN A 185.95.218.42"
local-data: "dns.digitale-gesellschaft.ch. IN AAAA 2a05:fc84::43"
local-data: "anycast.uncensoreddns.org. IN A 91.239.100.100"
local-data: "anycast.uncensoreddns.org. IN AAAA 2001:67c:28a4::"
local-data: "dns10.quad9.net. IN A 9.9.9.10"
local-data: "dns10.quad9.net. IN AAAA 2620:fe::fe:10"
local-data: "example.com. IN A 104.20.23.154"
local-data: "example.com. IN AAAA 2606:4700:10::ac42:93f3"
local-data: "one.one.one.one. IN A 1.1.1.1"
local-data: "one.one.one.one. IN AAAA 2606:4700:4700::1001"
